baseURL = "https://amolchavan.space/"
languageCode = "en-us"
title = "Amol Chavan"
theme = "minimal"
GoogleAnalytics = "UA-142975356-1"
[params]
    author = "Amol Chavan"
#    description = "Personal blog theme powered by Hugo"
    githubUsername = "#"
    accent = "Blue"
    showBorder = true
    backgroundColor = "white"
#  font = "Roboto" # should match the name on Google Fonts!
    font = "Montserrat:400,700|Robot:400,400italic,700|Robot+Mono"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "java", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "https://amolchavan.space"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/



[[menu.icon]]
    url = "https://github.com/4m01/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/AmolChavan_"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/4m01"
    name = "linkedin"
    weight = 3

[[menu.icon]]
    url = "https://stackoverflow.com/users/1115090/4m01/"
    name = "stack-overflow"
    weight = 4

[[menu.button]]
    url = "https://us1.list-manage.com/contact-form?u=fbba080f6d88fe73f2b7a483e&form_id=d433fe0258eff8e32f01c788cd840c2e"
    name = ""
    weight = 5
